package com.inventra.app.presentation.inventory

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.inventra.app.data.repository.InventraRepository
import com.inventra.app.domain.model.InventoryItem
import com.inventra.app.domain.model.StockStatus
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject

data class InventorySummary(
    val totalProducts: Int,
    val totalUnits: Double,
    val totalValue: Double
)

@HiltViewModel
class InventoryViewModel @Inject constructor(
    private val repository: InventraRepository
) : ViewModel() {

    val inventoryItems: StateFlow<List<InventoryItem>> = repository.getInventoryItems()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val summary: StateFlow<InventorySummary> = inventoryItems
        .map { items ->
            InventorySummary(
                totalProducts = items.size,
                totalUnits = items.sumOf { it.product.currentStockQty },
                totalValue = items.sumOf { it.stockValue }
            )
        }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), InventorySummary(0, 0.0, 0.0))

    fun buildShareText(items: List<InventoryItem>, currencySymbol: String = "$"): String {
        val date = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date())
        val fmt = NumberFormat.getNumberInstance(Locale.getDefault())
        fmt.maximumFractionDigits = 2

        val sb = StringBuilder()
        sb.appendLine("📦 INVENTORY REPORT")
        sb.appendLine("Date: $date")
        sb.appendLine("─".repeat(40))
        sb.appendLine(String.format("%-22s %6s  %10s", "PRODUCT", "QTY", "VALUE"))
        sb.appendLine("─".repeat(40))

        items.sortedBy { it.product.name }.forEach { item ->
            val statusMark = when (item.stockStatus) {
                StockStatus.OUT -> "❌"
                StockStatus.LOW -> "⚠️"
                StockStatus.OK  -> "✅"
            }
            val name = item.product.name.take(20)
            val qty = fmt.format(item.product.currentStockQty)
            val value = "$currencySymbol${fmt.format(item.stockValue)}"
            sb.appendLine("$statusMark ${name.padEnd(20)} ${qty.padStart(6)}  ${value.padStart(10)}")
        }

        sb.appendLine("─".repeat(40))
        val totalValue = items.sumOf { it.stockValue }
        sb.appendLine("Total Stock Value: $currencySymbol${fmt.format(totalValue)}")
        sb.appendLine()
        sb.appendLine("✅ In Stock  ⚠️ Low Stock  ❌ Out of Stock")
        sb.appendLine("Generated by Inventra")
        return sb.toString()
    }
}
